name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'
      
    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Create ZIP Archive
      run: zip -r build.zip build

    - name: Upload ZIP Archive to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: ./build.zip
        target: ./public_html

    - name: SSH into Server and Extract ZIP Archive
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -v "${{ secrets.SSH_USERNAME }}"@"${{ secrets.SSH_HOST }}" 'cd /public_html && unzip -o build.zip'
    - name: Clean Up
      run: rm build.zip
