# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "cms-contentful" ]
  pull_request:
    branches: [ "cms-contentful" ]

jobs:
  build:
    env: 
      REACT_APP_CONTENTFUL_ID: $REACT_APP_CONTENTFUL_ID
      REACT_APP_CONTENTFUL_TOCKEN: $REACT_APP_CONTENTFUL_TOCKEN
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        
        with:
          node-version: '20.9.0'
        
      - name: Install Dependencies
        run: npm install
        
      - name: Test Project
        run: npm run test